In [1]:
import numpy as np
import pandas as pd
import torch
import os
import time

from transformers import Trainer, TrainingArguments
from datasets import load_dataset
from peft import PromptTuningConfig, get_peft_model
from peft import LoraConfig, get_peft_model, TaskType

from metrics import calculate_meteor_score, calculate_bleu_score
from tools import (inference_batch, get_model, tokenize_function, print_number_of_trainable_model_parameters,
                   format_inference_shots, format_input_texts)

os.environ["TOKENIZERS_PARALLELISM"] = "false"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

/home/denis/ax/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
[nltk_data] Downloading package punkt_tab to /home/denis/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to /home/denis/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

# Tarefa 1

## <span style="color:#FFA500"> Utilizando novamente o dataset de TESTE e o modelo ajustado na tarefa 2, execute mais uma vez as instruções da coluna “instruction” do dataset. Extraia 2 partes do dataset com 3000 linhas cada uma. Uma das partes será o dataset de treino e a outra, o de teste.Você pode escolher as linhas de cada dataset da forma que preferir.</span>

In [2]:
dataset_name = 'tatsu-lab/alpaca'

dataset = load_dataset(dataset_name)
dataset['train'].num_rows

52002

In [3]:
test_size = 3000
train_size = 3000
inference_input_idx = 5

idx = np.random.choice(dataset['train'].shape[0], size=train_size + test_size + inference_input_idx, replace=False)
traind_idx = idx[:train_size]
test_idx = idx[train_size:-inference_input_idx]
inference_input_idx = idx[-inference_input_idx:]
train_dataset = dataset.copy()['train'].select(traind_idx)
test_dataset = dataset.copy()['train'].select(test_idx)
inference_dataset = dataset.copy()['train'].select(inference_input_idx)

print(f'Train data size: {len(train_dataset)}\nTest data size: {len(test_dataset)}\nInference data size: {len(inference_dataset)}')

Train data size: 3000
Test data size: 3000
Inference data size: 5

## <span style="color:#FFA500">Utilizando o modelo indicado, execute as instruções da coluna “instruction” do dataset de TESTE.</span>

### Sem usar template de prompt

In [4]:
model, tokenizer = get_model(device)
print(print_number_of_trainable_model_parameters(model))

trainable model parameters: 124439808
all model parameters: 124439808
percentage of trainable model parameters: 100.00%

In [5]:
result_df = pd.DataFrame()
result_df['instruction'] = test_dataset['instruction']
result_df['reference'] = test_dataset['output']
result_df['prediction'] = inference_batch(test_dataset['instruction'], model, tokenizer, device)

Progress: [#############################] [3000/3000]

In [6]:
for i in result_df.index[:10]:
    print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
    print('\n' + ('-' * 150))

Instruction: Edit the sentence, “A king can no longer test the mettle of his knights by challenge to single combat” to make it easier to read.
Response: ‧ That, and the fact that you only need to read one sentence in order to take part in this event, to take advantage of our rewards.›

"Alright, so it looks like the rest of your team did it, as well?"

At the top of the page, the screen showed three "BATTLE" words in short sentences, each containing a different combatant, one of which was named "Archie".

It was a short message.

The only difference in the sentence was that the "Archer" text was in a different language, while the other two words were in English.



If you click on it, you will be taken to the battle page in English, but you won't be able to get a better idea of what was happening as you've entered the battle.


For example, if you click the picture, the text of the battle will be blacked out (without "Archery", "
Reference: A king can no longer assess the strength and courage of his knights by offering them a single combat challenge.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: What is the area of a triangle with base 8 cm and height 5 cm?
Response: A triangle is not a straight line. A triangle is a flat square. A straight line is a straight-line. A height is a length of a point. A rectangle is a rectangle on a diagonal axis. A square is an integer with length or height. A center is a circle. A number is a number with radius 4. A point is a point on a plane. A cube is a cube on an axis (and all other non-cube things in the system are "point" on their plane, too). (It would not be a triangle to have multiple points, since each point is represented by a number. But that's not a problem for you.) So in our case, we would say we are talking about the point 2 in the triangle. But what if we had to be really honest. To think that I know a thing or two about what is good and evil (i.e., what I really believe), I would say that it is impossible for
Reference: The area of the triangle is 20 cm squared.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Create a timeline to showcase important events in the history of AI.
Response: The first event will be hosted on May 1st, when the American Geophysical Union's "Conversion of Modern Time" will bring the world to the realization of the human race's vision for space exploration and colonization.

After this event, the team of experts, led by Dr. Steve Litchfield of the Center for Advanced Study at the University of Michigan, will host a series of meeting and workshop sessions in March. The goal of the meetings is to facilitate a scientific, collaborative, and respectful conversation on all aspects of life on Earth.
.
Reference: 1943: The first paper on AI is published by Warren McCulloch an Walter Pitts.

1956: John McCarthy coins the term “artificial intelligence.”

1966: Joseph Weizenbaum creates ELIZA, the first chatbot.

1971: Control Data Corporation crafts a chess-playing computer called Belle, which is the first computer to challenge a human chess champion.

1982: The first expert system, XCON, is developed at the Digital Equipment Corporation.

1997: Deep Blue (IBM) defeats world chess champion Garry Kasparov.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Compare and contrast militarism and imperialism
Response: to a more political view of things. The "political revolution" is about the people. It's about building power that can be used to fight for those who want it, and they can do it and they'll be rewarded with power. (This is true of the Chinese communists and other revolutions.) When an army is brought to bear, it's not about whether the regime is able to control it, it is about what the state is able and can do. It is about, not necessarily, when a dictator takes power, but when he does it and does it well. It should be one thing to have a powerful army, but to have the military as the power of the proletariat and a powerful people to be part of the revolutionary process. It shouldn't be an act of revolution but a real process.

Now, there are many theories about the role of the "People's Republic" in world history. One of the most popular is the Soviet model. A lot of the world
Reference: Militarism and imperialism are both forms of aggressive foreign policy, but they differ in terms of their motivations. Militarism refers to an aggressive foreign policy motivated by military strength and expanding influence, while imperialism is a foreign policy that is motivated by economic gains, control of resources, and the spread of a particular culture.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Create a story about a student who had an upcoming exam and was studying with his friends.
Response: The class consisted of a computer game called "In Memoriam".

A group of classmates played an online game called A "where the player is supposed to choose the name of the person with the most points." The students had to make decisions about which one to play and who to believe as to which they believed would win, such as a girl with a higher score who would win with more points. The students then played one of two ways for this student to win. "I could pick and choose which of the two sides of the question would win by the end of the class," a student told me. "My first choice was either to win or lose (if I was winning, I would try to stop the student playing in the round), and my second choice was to win and lose as well."

In fact, the student who was winning was the one who actually had more points than the other students (in fact, he had more than half of the points for each side
Reference: Jack was a hardworking student who was determined to pass his upcoming exam with flying colors. He had been studying diligently for weeks, but when the night before the exam arrived, he decided to take a break and seek help from his friends. He and his friends gathered around, poring over textbooks and notes, making sure that every detail was drilled into their memories. Their jokes and laughter created a sense of comfort and Jack, who had once felt stressed, was now more confident and ready for his exam.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Write 3-4 sentences about the benefits of using an online scheduler.
Response: "I think a lot of the things we're doing in the IT community are making life easier for people on a personal level, and when it comes to doing things like that, for a lot to be really good, for somebody to have the option of going out and doing all of that is a good thing," said Thomas.
- with the help of the Media Matters for America.
…
Reference: Using an online scheduler can provide many benefits. It can save time by automatically sending reminders to customers, eliminating the need for customer calls and emails. It can also reduce the cost of customer scheduling, since many online schedulers are low-cost or free. Additionally, online schedulers can help to ensure customer satisfaction by providing accurate appointment times that are easy to book. Finally, online schedulers can also help businesses to keep better track of their appointments and scheduling activity.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: What is Machine Learning?
Response: What can I do to make it better?

Machine learning is about solving problems. In this article I will focus on the concepts of problem solving and machine learning, as they relate to one another and to the development of new types of systems and algorithms. I will also be exploring the application of machine learning to business analysis, analytical planning, and learning from large datasets.

To be effective in these areas, an algorithm must have both the "right" and the "wrong" input. Machine learning is a type of problem that is designed to answer such queries as "What is the problem?" and "What should I do with my data?" That being said, the following algorithms will be used to solve the problems (although I will define a few of them).

I'll use these algorithms to solve any problem I might have, and to help others find the right solution.
.NET Core

.Net Core is a distributed machine learning library that is built on top of
Reference: Machine Learning is a type of Artificial Intelligence (AI) that gives computers the ability to learn without explicit programming. Machine learning algorithms use data to build models that make predictions on unseen data. Machine Learning is used in many applications including speech recognition, computer vision, recommendation systems, medical diagnosis, discover insights in data, and autonomous vehicles.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Give an example of an input for the following instruction: "Describe the effects of global warming".
Response: If you do not have the time and inclination to read the instruction, you may want to try to find the source code yourself, by copying it over with python: cp -r http://www.wattsupwiththat.com/2011/10/18/inverse-global-warming-couple-for-a-little-time/ ./configure --with-python [sudo]

Note: This example assumes you have run sudo before your program (see Configure Output ).

If you do have sudo installed, you can easily run python.

The code below should show you how the output of these commands is displayed. Note that this example assumes there is an input file to be saved, so that you can see what is being saved.
Reference: Global warming has caused rising sea levels, changes in precipitation patterns, affecting the timing and intensity of precipitation, more frequent and severe weather events such as heat waves, droughts, floods, and a stronger hurricane season, increased ocean acidification, melting of Arctic and Antarctic ice, and more.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Design an effective study plan.
Response: In order to ensure a good study plan we use the following principles:

1. The study will determine the best outcome and provide a baseline of all participants.
 (See: What Do I Know About the Study Plan?).

2. The Study Plan will contain all relevant information about the participants. It is a set of rules and guidelines that are based on the research findings. This will provide a good reference for the researchers to learn more about the study and to identify any potential conflicts.
 "You don't have to have any prior research to understand a particular point of study." -Dr. H. T. Brown, Professor of Psychology, University of Massachusetts Amherst.
.
, and. "You do not have to know how to conduct a study. The only difference is how the study is conducted." - Dr. T and Dr. R. Hagan.
 -Drs Dr. Brown and Brown and Hagan and Drs Brown and
Reference: An effective study plan should include setting clear and specific goals, breaking those goals down into achievable tasks, scheduling study sessions, taking regular breaks and rewarding yourself for completing each task. It should also include organizing your materials, studying in different places, finding a study partner, and using study techniques like spacing, review, practice and elaboration.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Generate a list of 10 slang words that are used in the United Kingdom.
Response: You'll notice that only some of these words are actually spelled differently (and some are spelled quite differently). These words are called 'symbols', 'claws', 'boots', and 'horns'. However, they are not words you'll get in a dictionary. If you're looking to learn how to pronounce the words 'girly', 'smooth', 'humble', 'frugal', or 'salty', look no further than 'leisure'.

It's a bit easier to find ways to be more inclusive when you find these words, but there are ways you can use these words in different contexts. One is to type them in. Use it when you can. Use them when you are comfortable having these words on your lips.
: if you start typing in the word 'salt', you get some of the other meanings listed below.
 and : if you are typing in any of the 'spaces', you will see
Reference: 1. Muppet - an idiot
2. Bloke - a man
3. Dodgy - of uncertain quality
4. Skive - to avoid work
5. Naff - not fashionable
6. Wazzock - an annoying person
7. Newt - great, awesome
8. Bumfluff - random string of words
9. Dosh - money
10. Bash - a party or event

------------------------------------------------------------------------------------------------------------------------------------------------------

In [7]:
general_results = {}
result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

general_results['without_prompt_and_ft'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                          axis=1).mean().to_dict()
general_results['without_prompt_and_ft']

{'bleu': 0.003931185484904012, 'meteor': 0.14030528065667675}

In [8]:
result_df.head()

,instruction,reference,prediction,bleu,meteor
0,"Edit the sentence, “A king can no longer test ...",A king can no longer assess the strength and c...,"‧ That, and the fact that you only need to rea...",0.001705,0.094851
1,What is the area of a triangle with base 8 cm ...,The area of the triangle is 20 cm squared.,A triangle is not a straight line. A triangle ...,0.002702,0.168278
2,Create a timeline to showcase important events...,1943: The first paper on AI is published by Wa...,"The first event will be hosted on May 1st, whe...",0.008404,0.138151
3,Compare and contrast militarism and imperialism,Militarism and imperialism are both forms of a...,"to a more political view of things. The ""polit...",0.002259,0.189445
4,Create a story about a student who had an upco...,Jack was a hardworking student who was determi...,The class consisted of a computer game called ...,0.008605,0.201317

## <span style="color:#FFA500">Avalie a qualidade do resultado. As respostas estavam corretas? Quais métodos podem ser usados para melhorá-las?</span>

---
<span style="color:#00BFFF">Resposta: Tanto os valores retornados nas métricas de avaliação, quanto os outputs gerados pelo modelo, não são bons... Isso já era um comportamento esperado, pois o modelo "ComCom/gpt2-small" além de pequeno foi treinado apenas para completar texto. Podemos utilizar métodos de prompt engineering, inserir shots de inferência dentro dos inputs para aumentar a chance de o modelo entender o padrão das tarefas solicitadas.</span>

### Usando template de prompt

#### Zero-shot inference

In [9]:
n_shots = 0
inference_shots = format_inference_shots(inference_dataset, n_shots)
print(inference_shots)

In [10]:
input_texts_0s = format_input_texts(test_dataset, inference_shots)

result_df = pd.DataFrame()
result_df['instruction'] = test_dataset['instruction']
result_df['reference'] = test_dataset['output']
result_df['prediction'] = inference_batch(input_texts_0s, model, tokenizer, device)

Progress: [#############################] [3000/3000]

In [11]:
for i in result_df.index[:10]:
    print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
    print('\n' + ('-' * 150))

Instruction: Edit the sentence, “A king can no longer test the mettle of his knights by challenge to single combat” to make it easier to read.
Response: Write an input.
...


In a similar manner to the command below, you will need to send the following messages, and they will be provided by the above command.
The first message would be to read a response from the command at the prompt. When you type "send", it's to send a message that your browser has set up.
This is a very simple command. As mentioned in the previous example, a "command" is a file in your browser and must contain the following information:
The target command (to read a reply) is to read it from the browser and to send it to the server. This is done by using a file extension called "reply.json". To send the file you would use this command. By adding the following to the output of "send":


{ "name": "John", "type": "file", "response": { "type" : "file" } }

The second message would simply
Reference: A king can no longer assess the strength and courage of his knights by offering them a single combat challenge.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: What is the area of a triangle with base 8 cm and height 5 cm?
Response: What has been written for this task? The first two are for `text` text in the `text_mode' file.


// In the text_mode file, there is an `text' element.

# We need a different element for this section.
 (useful for testing on a different project...)

// The `text mode' file needs to be able to handle all `texts' except `text.text_type`

(useful on a project...)


# A `text/text.txt' file is needed to print the message.



(echo "Text in `textmode' is `text').


## Response: (text -> text -> text)


msg `Text in the textmode file is `data`.


" )


Inheritance

We have an idea for some new code. We have already used an old `bases' (e.g
Reference: The area of the triangle is 20 cm squared.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Create a timeline to showcase important events in the history of AI.
Response: Create an action on the timeline that will show you the current events of the current time.
, this has the same set of parameters as for the original, but now includes a message.
. I am writing this as an interactive example and I wanted to give you a bit more information about what I am trying to get at.
In the response below you can see what the response looks like.
Example:
http://www.reddit.com/r/AI/comments/11t0t8/what_is_the_next_day_for_website_with_hq_to_keep/ I also want to get to the details of the time. You can click on the image to see the interactive version.
This will give you some idea of what you will be able to expect from this.
## Response:  # Response: # Reply to: ______.
# Input:
. As you can tell
Reference: 1943: The first paper on AI is published by Warren McCulloch an Walter Pitts.

1956: John McCarthy coins the term “artificial intelligence.”

1966: Joseph Weizenbaum creates ELIZA, the first chatbot.

1971: Control Data Corporation crafts a chess-playing computer called Belle, which is the first computer to challenge a human chess champion.

1982: The first expert system, XCON, is developed at the Digital Equipment Corporation.

1997: Deep Blue (IBM) defeats world chess champion Garry Kasparov.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Compare and contrast militarism and imperialism
Response: ## Response is good, and it is done with a simple message

# Response message must be formatted in a consistent way

> ############################################################

I was curious if anyone could tell me more about this. One of the main reasons that I wanted to write a book about this is because there are many questions that still remain unanswered. I would like to put this question in a more technical context and say how do we deal with it now? As far as the answer is based on the above mentioned examples, I was curious to see what type of system to have in place. After some time I was able to find some information that I did not have, and I went back and read all the answers to the questions.

The reason that I decided to write the book is that I want to find out the type of systems in place, and the answer that I get is that of the military, or the United States of America. This is a common question
Reference: Militarism and imperialism are both forms of aggressive foreign policy, but they differ in terms of their motivations. Militarism refers to an aggressive foreign policy motivated by military strength and expanding influence, while imperialism is a foreign policy that is motivated by economic gains, control of resources, and the spread of a particular culture.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Create a story about a student who had an upcoming exam and was studying with his friends.
Response: A student with a previous assignment at an ESL college in the US, asked a question that had the following meaning:

,

He started reading in English to meet his English teacher, and then got a lecture that he is still working on (and did this in a separate class at his ESL college:

.
:
"He stopped reading, but then he was in class, and his teacher began to teach him the word "heh".


" He told me the word he had learned while he was reading was "heo". "


If he had to memorize a word from a book, and to write a letter to a friend, then that book was a "he." The word that the teacher had brought him didn't have a "He" (he was able to write it on paper) and could have been written on a piece of paper, or simply by his hand.


.
 " His teacher instructed him to write an additional
Reference: Jack was a hardworking student who was determined to pass his upcoming exam with flying colors. He had been studying diligently for weeks, but when the night before the exam arrived, he decided to take a break and seek help from his friends. He and his friends gathered around, poring over textbooks and notes, making sure that every detail was drilled into their memories. Their jokes and laughter created a sense of comfort and Jack, who had once felt stressed, was now more confident and ready for his exam.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Write 3-4 sentences about the benefits of using an online scheduler.
Response: Write 1 sentence about the need for a scheduler that is not the same as the online scheduling.
.
 (The online schedulers may work differently when the program is running on the wrong CPU.)

(If the program needs to be interrupted, the scheduler may not be sufficient.)


Here is an example of a simple online scheduard. This is a 2-3 hour work. This will take you about 3 minutes to complete the task.



## Response:

.
... In the case of a 2 hour task and you don't want to interrupt it, write "hello world" to the command line. This program will ask you to do a few things to this web page.
* Make sure you can follow the instructions as instructed. * Make sure to write the "Hello World" response as well as the "hello" and "world" text. (Note that if the program you are running is a 3 minute task
Reference: Using an online scheduler can provide many benefits. It can save time by automatically sending reminders to customers, eliminating the need for customer calls and emails. It can also reduce the cost of customer scheduling, since many online schedulers are low-cost or free. Additionally, online schedulers can help to ensure customer satisfaction by providing accurate appointment times that are easy to book. Finally, online schedulers can also help businesses to keep better track of their appointments and scheduling activity.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: What is Machine Learning?
Response: This is a very simple problem. A simple response, followed by a series of values (not to be confused with the series of numbers we defined in the previous section). A series of "lines" of the message will be a sequence of the current value of the input. The number of lines in the series will be the total of all lines in this series, and that number, as specified in the current line, will be computed by the given value.

What we are going to learn are the basic operations of Machine Learning, in this case:



>>> from random import (

--

| n, n == 1?
.to_int

.set_to_integer(n)

),

>>>

n=1 + 6

-12

+ 3

*n * n

)


--


[{

...

}]

where N is the number
Reference: Machine Learning is a type of Artificial Intelligence (AI) that gives computers the ability to learn without explicit programming. Machine learning algorithms use data to build models that make predictions on unseen data. Machine Learning is used in many applications including speech recognition, computer vision, recommendation systems, medical diagnosis, discover insights in data, and autonomous vehicles.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Give an example of an input for the following instruction: "Describe the effects of global warming".
Response: Write a response for a response sent by a response sender. Write the response to http://example.com/dynamics/.

## Response:

. This is the raw response to the request. It is a list of values and an empty string.

#### Response: ### Input:
.
-{-# LANGUAGE OverloadedStrings #-}

#-{--] #-

-[-] *

import qualified Data.Decoder.Decodable as Decodable

static Data.String str_name = ""

assert str_names. equals ( str_new , [])

}
(

"Dynamics": {

// "TODO: Remove and change the string value (but remove the string), in case it is too long, etc."

).

def __init__ ( self , name ):

self .name =
Reference: Global warming has caused rising sea levels, changes in precipitation patterns, affecting the timing and intensity of precipitation, more frequent and severe weather events such as heat waves, droughts, floods, and a stronger hurricane season, increased ocean acidification, melting of Arctic and Antarctic ice, and more.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Design an effective study plan.
Response: Include a description of the desired task, a description, as the task is completed, including the required information.
 (Example: "The Study Set is not included with the schedule.")

## Response:

?*

The study is not completed. (example: "This task may be completed on time and has a minimum of 20 minutes.")


?

How long is the study, or what are the required steps?


*
.
.


In the order in which you want to work, and in the order of priorities. There is a way to choose the first, and the second, and third, and so forth. It is not important which one you want. I will give you a quick idea of the order to work from if you wish to work more. The important thing is to think about the "correct" order in your mind. The question is:
The problem is to determine when to work the task.
Reference: An effective study plan should include setting clear and specific goals, breaking those goals down into achievable tasks, scheduling study sessions, taking regular breaks and rewarding yourself for completing each task. It should also include organizing your materials, studying in different places, finding a study partner, and using study techniques like spacing, review, practice and elaboration.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Generate a list of 10 slang words that are used in the United Kingdom.
Response: Generated by:
… and is being used in:
.


This is a problem. There are so many slang words and they are all different for each country. For each country, there are some English words that do not match.
The last three commands are:



#### Response:

 (You are doing good work and I'm pleased with the results.)


For more instructions, see the FAQ. If you find that one sentence does not end in an answer, please let me know and I will add it to the FAQ as well.
Here is the problem with this approach. In most languages, you can still write down the results of each request, but it is far more important to have the entire sentence written down. To solve this problem, I have created a script that generates some numbers from the English language so I can read in the English word list and match them with what I was used to with the original request. It is based on
Reference: 1. Muppet - an idiot
2. Bloke - a man
3. Dodgy - of uncertain quality
4. Skive - to avoid work
5. Naff - not fashionable
6. Wazzock - an annoying person
7. Newt - great, awesome
8. Bumfluff - random string of words
9. Dosh - money
10. Bash - a party or event

------------------------------------------------------------------------------------------------------------------------------------------------------

In [12]:
result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

general_results['prompt_eng_0shot'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                          axis=1).mean().to_dict()
general_results['prompt_eng_0shot']

{'bleu': 0.003676067222122717, 'meteor': 0.12885171299150597}

In [13]:
result_df.head()

,instruction,reference,prediction,bleu,meteor
0,"Edit the sentence, “A king can no longer test ...",A king can no longer assess the strength and c...,Write an input.\n...\n\n\nIn a similar manner ...,0.001779,0.104167
1,What is the area of a triangle with base 8 cm ...,The area of the triangle is 20 cm squared.,What has been written for this task? The first...,0.002099,0.079681
2,Create a timeline to showcase important events...,1943: The first paper on AI is published by Wa...,Create an action on the timeline that will sho...,0.002435,0.152749
3,Compare and contrast militarism and imperialism,Militarism and imperialism are both forms of a...,"## Response is good, and it is done with a sim...",0.004310,0.158831
4,Create a story about a student who had an upco...,Jack was a hardworking student who was determi...,A student with a previous assignment at an ESL...,0.005599,0.236481

#### One shot inference

In [14]:
n_shots = 1
inference_shots = format_inference_shots(inference_dataset, n_shots)
print(inference_shots)

Below are 1 instructions that describe task resolutions. First comes ### Instruction, providing the instruction to be followed. Second comes ### Input, providing information that supports the instruction. And last comes ### Response, bringing the response to this instruction.
### Instruction:
Develop a research question that can be answered using data.

### Input:
Traffic congestion

### Response:
What factors contribute to traffic congestion in city centers?

In [15]:
input_texts_1s = format_input_texts(test_dataset, inference_shots)

result_df = pd.DataFrame()
result_df['instruction'] = test_dataset['instruction']
result_df['reference'] = test_dataset['output']
result_df['prediction'] = inference_batch(input_texts_1s, model, tokenizer, device)

Progress: [#############################] [3000/3000]

In [16]:
for i in result_df.index[:10]:
    print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
    print('\n' + ('-' * 150))

Instruction: Edit the sentence, “A king can no longer test the mettle of his knights by challenge to single combat” to make it easier to read.
Response: The queen has a high desire to see one's children and can no more take it away than she can, so she will need some money to pay for her children's education. The king can then send her a letter by mail asking if the child is suitable for education, or if his parents are willing to pay.
"If my child is a good child who is at home and will meet you in the summer, I will send him to a well-off and well-educated woman, so that you may not be disappointed in his education. I will also give you a suitable place to live."

###### Response: The answer is "Yes, but you are not allowed to marry in a well placed place like the palace or your home." ### Response:

.
.



# Response: (to a servant)

"Sir, how about this? I can't marry."


.


"Why should I?"


The answer
Reference: A king can no longer assess the strength and courage of his knights by offering them a single combat challenge.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: What is the area of a triangle with base 8 cm and height 5 cm?
Response: What are the height of the triangle with the base 8cm and height 3.2 cm?

-


As a result of a design, you can see that the dimensions of the triangles are 3.5 cm / 5.4 cm and the base 7.6 cm / 1.5 mm.


The base 7 inch height of your triangle is 1.4 m.
, it is about 3 mm wide.
. If your base 9 inch height is 3.6 m or higher, your triangle will have a base of 3.0 cm.
-

.
And here is another example of the 3.7 cm base 7 inches.



In this triangle, you may also see the base of 1.9 cm / 6.2 inch.
)

.
'

The above instruction is for a simple example of using the data to calculate a score. It is based on a basic approach which is very easy to learn in
Reference: The area of the triangle is 20 cm squared.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Create a timeline to showcase important events in the history of AI.
Response: How important is this event to the system?

There are several ways to make this relevant to the future. The first is using AI as a backdrop. The most effective way to make AI relevant to public interest requires a large amount of time and attention.
The second is to utilize AI as the main driver of AI systems.
Here is an example of a major event in an AI system that would be connected to real-time traffic data: a real-life traffic situation. A significant portion of the current traffic is happening in cities and is generated by automated vehicles. This data is then filtered into a way to understand the context of the event. The results will be useful to the public. The data is filtered into the "real world" by automated traffic management algorithms, which provide information about the conditions and events of the situation. AI is an integral part of the process. The information collected from the data is processed in real time. It is then used to optimize AI systems for
Reference: 1943: The first paper on AI is published by Warren McCulloch an Walter Pitts.

1956: John McCarthy coins the term “artificial intelligence.”

1966: Joseph Weizenbaum creates ELIZA, the first chatbot.

1971: Control Data Corporation crafts a chess-playing computer called Belle, which is the first computer to challenge a human chess champion.

1982: The first expert system, XCON, is developed at the Digital Equipment Corporation.

1997: Deep Blue (IBM) defeats world chess champion Garry Kasparov.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Compare and contrast militarism and imperialism
Response: What is the best way to organize war?

## Response:

 I. Introduction

Let's start with the military sector. At the beginning of the 20th century, the United States fought for the right to defend itself from foreign invasion. This was the result of the end of the Cold War and the United Nations. Since then, the two sides have increasingly clashed on the world stage, with the United Kingdom (UK) and Russia (Rus) having the most extensive military cooperation. The United States has, however, found its share of success in the South China Sea, particularly with regard to the maritime rights in the region, notably by the United Arab Emirates (AQAM) and Brunei. Although these are a separate region, they have remained closely linked to the United Nation.
"I believe that, on the one hand, the situation of the United State of America should be a place where, as far as possible, it should be viewed as an ally in
Reference: Militarism and imperialism are both forms of aggressive foreign policy, but they differ in terms of their motivations. Militarism refers to an aggressive foreign policy motivated by military strength and expanding influence, while imperialism is a foreign policy that is motivated by economic gains, control of resources, and the spread of a particular culture.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Create a story about a student who had an upcoming exam and was studying with his friends.
Response: If the answer doesn't follow the goal, how would you rate the student on how hard was it to complete the study?

Conclusion

Here are some questions to ask yourself.


What do the questions help you think about?



How can I make this task as easy as possible?

, or

What questions can be helpful?
 "How do I know when this is the right time to do this?"


And some questions I asked myself.
Reference: Jack was a hardworking student who was determined to pass his upcoming exam with flying colors. He had been studying diligently for weeks, but when the night before the exam arrived, he decided to take a break and seek help from his friends. He and his friends gathered around, poring over textbooks and notes, making sure that every detail was drilled into their memories. Their jokes and laughter created a sense of comfort and Jack, who had once felt stressed, was now more confident and ready for his exam.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Write 3-4 sentences about the benefits of using an online scheduler.
Response: Responsibility for answering the question is to use the requested data and provide the results in a format that is accurate.
"A typical question can be asked in three ways:"

"What is a standard request format?"

Or, "What are the best practices to avoid sending messages with a short, but detailed description of how that data is used??"
.
…

Here is an example of a request format:
'{'{$.json}', '{'$.zip}', ''

}'

Outputs:
 - In a typical request format (as a single line, for example) the response is to send an email to @firm@google.com and @fianz@google for use for a week. If the response contains a full description of a query, then it is sent to the request. If it does not, the request is forwarded to the user for further processing. -
Reference: Using an online scheduler can provide many benefits. It can save time by automatically sending reminders to customers, eliminating the need for customer calls and emails. It can also reduce the cost of customer scheduling, since many online schedulers are low-cost or free. Additionally, online schedulers can help to ensure customer satisfaction by providing accurate appointment times that are easy to book. Finally, online schedulers can also help businesses to keep better track of their appointments and scheduling activity.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: What is Machine Learning?
Response: What are the most common questions that a questioner has to answer?




below is an example of a common question.


How to answer a "hard" question:

. The key is to do a simple search or simply ask some questions.

. If you have a question and it is not obvious to most, then a quick search (to find answer) might help.

, if you have the question, write a response and do a search.

 . If you are not sure, then do some research and ask the question. If it will help, try to find that specific topic.

: If you don't know what you are looking for, then look at the answers to the question that came from the questioner.
Reference: Machine Learning is a type of Artificial Intelligence (AI) that gives computers the ability to learn without explicit programming. Machine learning algorithms use data to build models that make predictions on unseen data. Machine Learning is used in many applications including speech recognition, computer vision, recommendation systems, medical diagnosis, discover insights in data, and autonomous vehicles.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Give an example of an input for the following instruction: "Describe the effects of global warming".
Response: When do you feel safe, and where do you want to spend the rest of your day?

#

What is the "best practice"?

"The best practice" is not an appropriate description for a specific task at this time, but what is a good practice to do as well. If you feel comfortable with your task, you can make suggestions and improve your skills.
 "The best practices" should help you to solve problems in your own way and with a better knowledge of the problem.
: You can do some practice in this way but this will often take time. Try to do it all at once and focus only on what you feel you can improve.
"A good practice is a practice that will help you reach your goal or accomplish your task.
.
, your work should be focused on one task. Your work should have the most impact on your ability to solve the problem in this context.
As a general rule: do not start
Reference: Global warming has caused rising sea levels, changes in precipitation patterns, affecting the timing and intensity of precipitation, more frequent and severe weather events such as heat waves, droughts, floods, and a stronger hurricane season, increased ocean acidification, melting of Arctic and Antarctic ice, and more.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Design an effective study plan.
Response: What are the factors that are driving traffic congestion?

:
The data that we collect, when the data is collected.
.
 of all of the traffic.
/ of the all traffic.


In order to understand this information, we need to look at traffic congestion. We can look at any single metric, such as the average time it takes to get from one place in a location to another, or the average number of trips that an individual travels. We need to take the same look at each metric. And here are some examples of metrics that people look at as driving a problem.
Here are a few different examples.
# Traffic:
There's a lot of congestion in traffic. It gets a lot worse, if traffic is high. Here's an example. An average daily user of the city gets a daily traffic. I've seen this happen in other cities, especially in New York City and Austin, Texas.
If we want to know what factors
Reference: An effective study plan should include setting clear and specific goals, breaking those goals down into achievable tasks, scheduling study sessions, taking regular breaks and rewarding yourself for completing each task. It should also include organizing your materials, studying in different places, finding a study partner, and using study techniques like spacing, review, practice and elaboration.

------------------------------------------------------------------------------------------------------------------------------------------------------
Instruction: Generate a list of 10 slang words that are used in the United Kingdom.
Response: How often is the phrase on the list used?

# How often does it occur?

:
Reference: 1. Muppet - an idiot
2. Bloke - a man
3. Dodgy - of uncertain quality
4. Skive - to avoid work
5. Naff - not fashionable
6. Wazzock - an annoying person
7. Newt - great, awesome
8. Bumfluff - random string of words
9. Dosh - money
10. Bash - a party or event

------------------------------------------------------------------------------------------------------------------------------------------------------

In [17]:
result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

general_results['prompt_eng_1shot'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                          axis=1).mean().to_dict()
general_results['prompt_eng_1shot']

{'bleu': 0.0037120767131626972, 'meteor': 0.12941832805613349}

In [18]:
result_df.head()

,instruction,reference,prediction,bleu,meteor
0,"Edit the sentence, “A king can no longer test ...",A king can no longer assess the strength and c...,The queen has a high desire to see one's child...,0.004202,0.168122
1,What is the area of a triangle with base 8 cm ...,The area of the triangle is 20 cm squared.,What are the height of the triangle with the b...,0.008016,0.142857
2,Create a timeline to showcase important events...,1943: The first paper on AI is published by Wa...,How important is this event to the system?\n\n...,0.004401,0.131323
3,Compare and contrast militarism and imperialism,Militarism and imperialism are both forms of a...,What is the best way to organize war?\n\n## Re...,0.004166,0.178082
4,Create a story about a student who had an upco...,Jack was a hardworking student who was determi...,"If the answer doesn't follow the goal, how wou...",0.003369,0.097336

### Few-shot inference

In [ ]:
n_shots = 3
inference_shots = format_inference_shots(inference_dataset, n_shots)
print(inference_shots)

Below are 5 instructions that describe task resolutions. First comes ### Instruction, providing the instruction to be followed. Second comes ### Input, providing information that supports the instruction. And last comes ### Response, bringing the response to this instruction.
### Instruction:
Develop a research question that can be answered using data.

### Input:
Traffic congestion

### Response:
What factors contribute to traffic congestion in city centers?


### Instruction:
Select three websites to research a topic.

### Input:


### Response:
Wikipedia, BBC, and The New York Times are three good sources for researching any topic.


### Instruction:
Give three example of plants that thrive in shade.

### Input:


### Response:
Examples of plants that thrive in shade include hostas, ferns, and impatiens. Hostas have large, colorful leaves and come in a variety of shapes and sizes. Ferns are often sold in pots and love shady areas. Impatiens are known for their bright colors, come in a range of shades and bloom throughout the year.


### Instruction:
Explain the concept of tax incentives.

### Input:


### Response:
Tax incentives are economic benefits offered by federal or state governments to encourage businesses and individuals to take specific economic or financial actions, such as investing in research and development, hiring employees, providing employee benefits, or investing in technological growth. They are typically offered in the form of tax credits, deductions, or deferrals that reduce individuals' or businesses' tax liability. By providing financial incentives, governments hope to stimulate economic growth and encourage investment in specific areas.


### Instruction:
Find the total number of employees working in the company

### Input:
The company ABC has 100 employees in its main office, 75 employees in its satellite office and 25 employees working remotely.

### Response:
The total number of employees working in the company ABC is 200.

In [21]:
input_texts_fs = format_input_texts(test_dataset, inference_shots)

result_df = pd.DataFrame()
result_df['instruction'] = test_dataset['instruction']
result_df['reference'] = test_dataset['output']
result_df['prediction'] = inference_batch(input_texts_fs, model, tokenizer, device, batch_size=30)

Progress: [###################################################                                                ] [1560/3000]

KeyboardInterrupt:

In [ ]:
for i in result_df.index[:10]:
    print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
    print('\n' + ('-' * 150))

In [ ]:
result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

general_results['prompt_eng_fs'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                          axis=1).mean().to_dict()
general_results['prompt_eng_fs']

In [ ]:
result_df.head()

## <span style="color:#FFA500">Avalie a qualidade do resultado. As respostas estavam corretas? Quais métodos podem ser usados para melhorá-las?</span>


---
<span style="color:#00BFFF">Resposta: Ao usar um template de prompt, os resultados...</span>

# Tarefa 2

## <span style="color:#FFA500"> Utilizando o dataset de TREINO, faça o ajuste (fine-tuning) do modelo. Você pode usar técnicas para simplificar o fine-tuning, ajustando um conjunto menor de parâmetros e consumindo menos memória.</span>

## <span style="color:#FFA500"> Utilizando novamente o dataset de TESTE e o modelo ajustado na tarefa 2, execute mais uma vez as instruções da coluna “instruction” do dataset.</span>

# Fine Tuning

In [ ]:
model, tokenizer = get_model(device)

In [ ]:
prompt = """Below is an instruction for a task. First comes ### Instruction, giving the instruction to be followed. Second comes ### Input, giving information that supports the instruction. Write a response that adequately completes the request from ### Response.
### Instruction:
{}

### Input:
{}

### Response:
"""

tokenized_train_dataset = train_dataset.map(lambda example: tokenize_function(example, prompt, tokenizer), batched=False)

### Prompt Tuning with Prompt template

In [ ]:
num_virtual_tokens = 30

peft_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=num_virtual_tokens,  # Número de tokens do prompt
    token_dim=model.config.hidden_size,         # Dimensão do embedding (768 para GPT-2 small)
    num_attention_heads=model.config.num_attention_heads # Número de heads de atenção do modelo
)

prompt_tuning_model = get_peft_model(model, peft_config)

In [ ]:
print(print_number_of_trainable_model_parameters(prompt_tuning_model))

In [ ]:
output_dir = f'./prompt-tuning-gpt2-alpaca-{str(int(time.time()))}'

peft_training_args = TrainingArguments(
    output_dir=output_dir,
    auto_find_batch_size=True,
    learning_rate=1e-3,
    logging_steps=100,
    max_steps=100,  # Aumentado para um valor mais útil
    remove_unused_columns=False,  # Importante para PEFT
    label_names=["input_ids"]  # Resolve o warning
)
    
peft_trainer = Trainer(
    model=prompt_tuning_model,
    args=peft_training_args,
    train_dataset=tokenized_train_dataset,
)

In [ ]:
peft_trainer.train()
peft_trainer.model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir, safe_serialization=True)

In [ ]:
input_types = {'0s': input_texts_0s,
               '1s': input_texts_1s,
               'fs': input_texts_fs
               }

for key, input_texts in input_types.items():
    result_df = pd.DataFrame()
    result_df['instruction'] = test_dataset['instruction']
    result_df['reference'] = test_dataset['output']
    result_df['prediction'] = inference_batch(input_texts, prompt_tuning_model, tokenizer, device, batch_size=30)

    result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
    result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

    general_results[f'prompt_tunning_{key}'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                            axis=1).mean().to_dict()
    general_results[f'prompt_tunning_{key}']

    for i in result_df.index[:3]:
        print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
        print('\n' + ('-' * 150))
    print('\n' + ('=' * 150))

In [ ]:
result_df.head()

### LoRA fine tuning with Prompt template

In [ ]:
model, tokenizer = get_model(device)

In [ ]:
lora_config = LoraConfig(
    r=512,
    lora_alpha=256,
    target_modules=["c_attn", "c_proj"],
    lora_dropout=0.1,
    bias="lora_only",
    task_type=TaskType.CAUSAL_LM
)

In [ ]:
peft_model = get_peft_model(model, lora_config)

In [ ]:
print(print_number_of_trainable_model_parameters(peft_model))

In [ ]:
output_dir = f'./loraft-gpt2-alpaca-{str(int(time.time()))}'

peft_training_args = TrainingArguments(
    output_dir=output_dir,
    auto_find_batch_size=True,
    save_safetensors=False,
    learning_rate=1e-3, # Taxa deve ser maior que no full fine tunning
    logging_steps=100,
    max_steps=100   
)
    
peft_trainer = Trainer(
    model=peft_model,
    args=peft_training_args,
    train_dataset=tokenized_train_dataset,
)

In [ ]:
peft_trainer.train()
peft_trainer.model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir, safe_serialization=True)

In [ ]:
for key, input_texts in input_types.items():
    result_df = pd.DataFrame()
    result_df['instruction'] = test_dataset['instruction']
    result_df['reference'] = test_dataset['output']
    result_df['prediction'] = inference_batch(input_texts, peft_model, tokenizer, device, batch_size=30)

    result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
    result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

    general_results[f'prompt_eng_and_lora_{key}'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                            axis=1).mean().to_dict()
    general_results[f'prompt_eng_and_lora_{key}']

    for i in result_df.index[:3]:
        print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
        print('\n' + ('-' * 150))
    print('\n' + ('=' * 150))

### Full fine tuning with Prompt template

In [ ]:
model, tokenizer = get_model(device)

In [ ]:
print(print_number_of_trainable_model_parameters(model))

In [ ]:
output_dir = f'./fullft-gpt2-alpaca-{str(int(time.time()))}'

peft_training_args = TrainingArguments(
    output_dir=output_dir,
    auto_find_batch_size=True,
    save_safetensors=False,
    learning_rate=1e-4,
    logging_steps=100,
    max_steps=100
)
    
trainer = Trainer(
    model=model,
    args=peft_training_args,
    train_dataset=tokenized_train_dataset,
)

In [ ]:
trainer.train()
trainer.model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir, safe_serialization=True)

In [ ]:
for key, input_texts in input_types.items():
    result_df = pd.DataFrame()
    result_df['instruction'] = test_dataset['instruction']
    result_df['reference'] = test_dataset['output']
    result_df['prediction'] = inference_batch(input_texts, model, tokenizer, device)

    result_df['bleu'] = calculate_bleu_score(result_df['prediction'], result_df['reference'])
    result_df['meteor'] = calculate_meteor_score(result_df['prediction'], result_df['reference'])

    general_results[f'prompt_eng_and_full_ft_{key}'] = result_df.drop(['instruction', 'prediction', 'reference'],
                                                            axis=1).mean().to_dict()
    general_results[f'prompt_eng_and_full_ft_{key}']

    for i in result_df.index[:3]:
        print(f"Instruction: {result_df['instruction'][i]}\nResponse: {result_df['prediction'][i]}\nReference: {result_df['reference'][i]}")
        print('\n' + ('-' * 150))
    print('\n' + ('=' * 150))

## <span style="color:#FFA500">Interprete os resultados em comparação com os obtidos na tarefa 1.</span>

In [ ]:
general_results_df = pd.DataFrame(general_results).T
general_results_df

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 10))
for i, metric in enumerate(general_results_df.columns):
    plt.subplot(1,2,i+1)
    sns.barplot(general_results_df, x=metric)
    # general_results_df.T[metric].plot(kind='bar')

<span style="color:#00BFFF">Resposta: Mesmo após os processos de fine tuning testados, os resultados não melhoraram o suficiente para que o modelo se adaptasse a seguir as instruções. Além disso, o conjunto de dados "tatsu-lab/alpaca" traz diversos tipos de tarefas diferentes (não categorizadas), dificultando ainda mais o fine tuning do modelo para tarefas específicas. Seria necessário termos muitos registros para cada tipo específico de tarefa, para que o modelo ficasse bom em todas elas. Uma alternativa de melhoria seria aumentar o conjunto de dados utilizados para treinamento, outra seria utilizar few-shot inferences com inferências específicas para a tarefa que deve ser solucionada.</span>

## <span style="color:#FFA500">Se você precisasse agrupar as perguntas que tratam de assuntos semelhantes nos 2 datasets, como faria?</span>
---
<span style="color:#00BFFF">Resposta: Poderia gerar embeddings semânticos das entradas da coluna "instruction" usando um modelo de embeddings semântico, que transforma cada frase em um vetor numérico representando seu significado. Com esses vetores, é possível aplicar um algoritmo de clusterização (como KMeans, DBSCAN ou HDBSCAN) para identificar grupos de instruções com temas ou propósitos parecidos, como traduções, resumos ou geração de código. Isso permite organizar o dataset por tipo de tarefa, facilitando análises, seleção de exemplos e melhorias no modelo.</span>